# RankGui plugin by SpaicyGaming.

#Il costo DEVE essere un NUMERO INTERO e NON decimale.
Inventory:
  name: "&a&lBuy Ranks"
  itemsMaterial: DIAMOND_CHESTPLATE
  # multipli di 9
  size: 45

# Il comando che verraà eseguito dalla console all'acquisto di un rank
dispatchedCommand: "pex user {player} group add {pex_name}"

# Gli oggetti nell'inventario
Items:
  rank1:    
    pexName: rank1
    name: '&b&lRank1'
    cost: 100
    # La posizione dell'inventario
    invPosition: 18
  rank2:    
    pexName: rank2
    name: '&b&lRank2'
    cost: 1000
    invPosition: 19
  rank3:    
    pexName: rank3
    name: '&b&lRank3'
    cost: 10000
    invPosition: 20
  rank4:    
    pexName: rank4
    name: '&b&lRank4'
    cost: 100000
    invPosition: 21
  rank5:    
    pexName: rank5
    name: '&b&lRank5'
    cost: 1000000
    invPosition: 22
#
# I lores degli items nella gui
# PlaceHolders:
# {price} -> Il costo del  rank
# {pex_name} -> Il nome del pex
# {name} -> Il nome dell'item
ItemsLores:
- ""
- "&bRank: {pex_name}"
- "&cPrezzo {price}$"

ConfirmGui:
  title: "&b&lConferma Acquisto"
  confirm:
    name: "&a&lConferma"
    lore:
    - "&7Cliccami per confermare"
    - "&7l'acquisto"
  cancel:
    name: "&c&lAnnulla"
    lore:
    - "&7Cliccami per annullare"
    - "&7l'acquisto"
  sign:
    name: "&bStai per acquistare:"
    lore:
    - "&7Rank: {pex}"
    - "&7Costo: {cost}"

Messages:
  prefix: "&7[&c&lRankGui&7] &r"
  noPerms: "&cMi spiace, non hai il permesso di farlo."
  notEnoughtMoney: '&cMi spiace, non hai abbastanza soldi!'
  wrongUsage: "&cUtilizzo corretto: /rankgui [reload]"
  actionCancelled: "&cAcquisto annullato con successo."
  pexBought: '&aComplimenti! Hai correttamente acquistato il rank {pex} &aper &l{cost}$!'