main: me.spaicygaming.rankgui.RankGui
author: SpaicyGaming
softdepend: [Vault, PermissionsEx]

name: RankGui
version: 1.2

commands:
  rankgui:
    description: Main command.
    aliases: [buyrank, buyranks]